nome = input('Digite o seu nome completo: ')
nomeu = nome.upper()
nomel = nome.lower()
nomelse = ''.join(nome.split())
pnome = nome.split()
print(nomeu)
print(nomel)
print(len(nomelse))
print(len(pnome[0]))